name: PlaceholderPlus
version: '${version}'
api-version: 1.13
main: org.verdurae.placeholderplus.PlaceholderPlus
author: Kaminy
depend:
  - PlaceholderAPI
website: https://github.com/Verdurae/PlaceholderPlus
folia-supported: true
commands:
  pp: